name: Hestia Fuel Sync

on:
  schedule:
    - cron: '0 * * * *' # Se ejecuta cada hora
  workflow_dispatch: # Esto permite que lo ejecutemos a mano para probar

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm install
      - name: Run sync script
        run: node update-fuel.js
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
